javac -d . UpdateBook.java
javac -d . AddUserServlet.java
javac -d . BookBean.java
javac -d . DeleteBook.java
javac -d . FindAllBooks.java
javac -d . FindBookByID.java
javac -d . HelloServlet.java
javac -d . LoginProcessServlet.java
javac -d . UserBean.java